# Generated by Django 3.1.2 on 2020-11-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='Registration_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
