# Generated by Django 3.1.2 on 2020-11-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='City',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
