# Generated by Django 3.1.2 on 2020-11-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20201105_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='r_logo',
            field=models.FileField(upload_to='rest_logo'),
        ),
    ]
