# Generated by Django 3.1.2 on 2020-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20201105_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='speciality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
