# Generated by Django 3.1.2 on 2020-11-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='val',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='menu',
            name='r_menu',
            field=models.ManyToManyField(to='foodapp.MenuItem'),
        ),
    ]
